### ISSUE TITLE
Error Messages On Initial Page Load

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#126]
When the UI first loads i receive error messages suggesting to enable CORS or to correct the beacon node connection. 

This is because it tries to connect to the default connection in order to provide the green tick. Although we want it make the initial connection as often the default may be the correct choices, we probably don't want to show these error messages on the first page load. Every subsequent attempt at connecting they would be valuable. 

If its easy to avoid on the first attempt, I think that would be a better UX

**Comment by rickimoore** [comment]
handled here https://github.com/sigp/siren/pull/129
