### ISSUE TITLE
retain field contents when switching between basic/advanced config

### ISSUE THREAD

**Issue by antondlr** [sigp/lighthouse-ui#128]
right now, when switching between `basic settings` and `advanced settings` , the beacon address, BN port, and VC port get reset to default.   
It would make more sense to me to:  
- retain BN and VC ports in both directions  (same fields different layout)  
- retain beacon address in both directions  (same field)  
- drop whatever is in `VC address` when going from advanced -> basic  
- maybe rename `beacon address` in the basic view to something that covers both?  

Feel free to close this if this is intended behaviour.

**Comment by rickimoore** [comment]
handled here https://github.com/sigp/siren/pull/129
