### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#184]
Some alerts that might be useful to add:

- We see a single crit error. "Alert Critical Error" 
- We see a single error: "Alert Error" 
- We see 5 or more warnings (in an hour window): alert that something is misbehaving
- Peer count drops below 20
- NAT is closed
- Attestation missed (this is for the future, we could parse the logs which would tell us when attestations are missed. These will show as errors. ) 
- Block produced - Again would have to parse the logs for a block production log. The log would look like: "Valid block from HTTP API" in the beacon node 
- If we go out of sync a warning alert saying either the EC or BN is out of sync
 
We might want to parse some of the error message in the alerts if we can. Like if there is a crit, somehow display the log message corresponding to the crit when they click on the alert. 

If there are multiple of the same error, I don't think we stack them. We just have a single one. Once the user acknowledges them or removes them, we add them back if there are more.

**Comment by rickimoore** [comment]
- [x] Crticical alerts
- [x] error alerts
- [x] 5 or more warnings
- [x] peer count alerts
- [x] nat alert
- [x] beacon sync alert
- [x] ec sync alert
- [x] alerts dissmisable
