### ISSUE TITLE
Setting a session password is difficult

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#192]
There are bunch of requirements that are not listed and its annoying to set a password. 

I try one it says: must be 12 characters. 
I make one with 12 characters, it says, must have a special character. 

Might be nice to list the requirements somewhere on the page, and maybe tick them off as the password is generated.

**Comment by rickimoore** [comment]
ah yea, talked about that with aqueel. im working on it now

**Comment by rickimoore** [comment]
addressed in https://github.com/sigp/siren/pull/193
