### ISSUE TITLE
Some feedback on Siren

### ISSUE THREAD

**Issue by chong-he** [sigp/lighthouse-ui#196]
Play around with Siren (installed using Docker from the `unstable` branch [39bd11f](https://github.com/sigp/siren/commit/39bd11f60c827219dadb040a5c3bbc1736805fe5) and have some feedbacks:

1. Under `Logs`, when no validators are present in the validator client, it shows:
![image](https://github.com/sigp/siren/assets/44791194/416f7452-22c6-412a-be7b-37b7efb5df12)
while the `vc` logs:
```INFO No validators present                   msg: see `lighthouse account validator create --help` or the HTTP API documentation, service: notifier```
The `No validators present` should be displayed after INFO in the UI. When there are validator(s), the UI displays the correct info.

On a side note, I just thought that it will be nice to have a scrolling bar for the logs.

2. The active validators shown under `Validator Management` seems to be the total validators, not active validators, as below (I have 2 active validators in my `vc` and 4 total validators)
![image](https://github.com/sigp/siren/assets/44791194/8b54b085-ddb7-4fd0-a724-be96cdeb54c2)

3. When entering Siren, it asks for Authentication where users can set a password. This can be skipped. However, if skipped, during `withdraw validator`, it is mandatory to enter a password. The solution here is to either making entering password optional in `withdrawal validator`, or enforcing mandatory password setup at the startup.

4. Some minor formatting issues under `Validator Management`, info for a particular validator:
![image](https://github.com/sigp/siren/assets/44791194/5791b028-93ba-4382-b5fc-866862dd7831)

5. I tried to withdraw a validator but it says:
![exit](https://github.com/sigp/siren/assets/44791194/61894190-faee-4397-b126-e603d3a72aa1)

**Comment by rickimoore** [comment]
1. Was explained that siren displays the log data by the keys its receives via the sse log api. This data was not present during given log.

2. handled in https://github.com/sigp/siren/pull/197

3. it was explained that siren defaults to the api-token to validate sensitive actions when session auth is not set.

4. could not recreate, however will keep looking into

5. handled in https://github.com/sigp/siren/pull/198
