### ISSUE TITLE
Green status icon shown even when the chain is behind

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse-ui#199]
**Describe the bug**
Blocks behind on the main page is quite large on the dev instance (91), but has a green status next to it.

**To Reproduce**
1. Go to main dashboard page, and observe the status icon on the top when node is behind.

**Expected behavior**
When the node is behind, it should show a warn status, perhaps ember icon

**Screenshots**
<img width="252" alt="Image Pasted at 2023-8-14 14-53" src="https://github.com/sigp/siren/assets/742762/6a51913d-c30f-47fb-88f0-3a6249dde2cc">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - Version 115.0.5790.170

**Comment by rickimoore** [comment]
This issue was due to slot times varying from local testnet to mainnet/goerli. Due to the inconsistency we decided to use the sync_distance provided by the beacon sync api endpoint.
