### ISSUE TITLE
Changes to Validator Client `voluntary_exit` endpoint response

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse-ui#217]
There is a non-compliance on the `voluntary_exit` endpoint response with the key manager API spec, and is being addressed in Lighthouse https://github.com/sigp/lighthouse/pull/4679 (still under review)

This is a small change to add a `data` layer to the response, but it's a breaking change for Siren and response type needs to be updated.

Existing response
```json
{"message":{"epoch":"196868","validator_index":"505597"},"signature":"0xhexsig"}
```

New response:
```json
{"data":{"message":{"epoch":"196868","validator_index":"505597"},"signature":"0xhexsig"}}
```

It might be worth supporting both response types in the UI for a little while so users aren't force to upgrade to the latest Lighthouse version.

**Comment by rickimoore** [comment]
https://github.com/sigp/siren/pull/220

addressed and merged in this pr
