### ISSUE TITLE
Release 1.0.1 pgp signature missing - gives HTTP 404

### ISSUE THREAD

**Issue by cobordism** [sigp/lighthouse-ui#218]
**Describe the bug**
When downloading the Ryuko Matoi release, the pgp signature for the linux binary give 404 - is missing.

https://github.com/sigp/siren/releases/download/v1.0.1/siren-v1.0.1-x86_64-unknown-linux-gnu.zip.asc

**To Reproduce**
1. Go to https://github.com/sigp/siren/releases/tag/v1.0.1
2. Click on [PGP Signature](https://github.com/sigp/siren/releases/download/v1.0.1/siren-v1.0.1-x86_64-unknown-linux-gnu.zip.asc) 
3. See error

**Expected behavior**
I expect to get the pgp signature for the released binary file

**Comment by antondlr** [comment]
thanks for bringing this to our attention, links are fixed now!
