### ISSUE TITLE
Server side connectivity

### ISSUE THREAD

**Issue by karalabe** [sigp/lighthouse-ui#219]
Currently Siren tries to connect to the beacon/validator client side. That's very unfortunate, because it requires exposing the two nodes to outside access.

A better model would be to allow running Siren in it's own container on a remote host, connecting itself directly to the two lighthouse nodes. Only the HTTP port needs to be exposed to the outside (which can be behind a VPN or whatnot).

The benefit is that I could have separate containers for the beacon client, validator client and siren, each running in the same (locked down) docker network. That would prevent any traffic from the outside reaching them, but it would permit unfettered access across one another.

**Comment by AgeManning** [comment]
Yep, this has been discussed (internally) for a while now. 

I believe its on our roadmap to introduce a backend to manage the connection for this reason. As we've got some external users also wanting this, we can aim to prioritize this.

**Comment by rickimoore** [comment]
This issue has been address in our v2.0.0 release 🎉 

https://github.com/sigp/siren/pull/263
