### ISSUE TITLE
Replace deprecated `hub` usage with `gh` in release workflow

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse-ui#225]
- The `hub` cli has been removed from the GitHub runners as of October 2, according to : https://github.com/actions/runner-images/issues/8362

We should replace usage of `hub` in our release workflow (ideally before the next release), similar to Lighthouse [#4839](https://github.com/sigp/lighthouse/pull/4839).

https://github.com/sigp/siren/blob/stable/.github/workflows/release.yml#L237

**Comment by antondlr** [comment]
fixed in https://github.com/sigp/siren/pull/240
