### ISSUE TITLE
Makefile needs updating

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#229]
When I run `make` the makefile does not rebuild the binary. 

We probably just need to clean the build files each run.

**Comment by antondlr** [comment]
now that we're pushing docker as the only supported method of running siren, do we need a working Makefile, or do we get rid of it altogether? (in a way, the Dockerfile replaces the Makefile)

**Comment by AgeManning** [comment]
Fair. Some people will prob want to build from source, but I guess they can follow our docs to do it.
