### ISSUE TITLE
Add a unit for CPU in the validator health check

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#91]
In the validator health check, I've noticed the CPU quantity doesn't have a unit. 
![hc](https://user-images.githubusercontent.com/7454587/214090213-fae815c2-818d-479b-83c7-f0956670f513.png)

**Comment by rickimoore** [comment]
issue resolved and merged in main with the following PR: https://github.com/sigp/lighthouse-ui/pull/94
