### ISSUE TITLE
RAM requirements can be reduced

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse-ui#92]
I noticed that we are getting a red health check for a node that has sufficient RAM and decent utilization. We can probably drop the requirements. 

![hc](https://user-images.githubusercontent.com/7454587/214090679-b4e31f73-f814-4a9a-972c-07be98b3e3ef.png)

I think the requirements should go based on free RAM.  The chart shows total ram, in this case ~16GB and that only 56% is used. So that means we have 16GB * (1-0.56) free RAM. 

I think it would be good if we had the following criteria based on free RAM:
- Green: 3GB+
- Yellow: 1-3GB
- Red: < 1GB

**Comment by rickimoore** [comment]
Resolved in the following merged pr https://github.com/sigp/lighthouse-ui/pull/95
